---
- hosts: localhost
  tasks:
  - name: REPLACE NEXUS IMAGE FOR FUTUTRE NEXUS RELEASES/VERSIONS
    replace:
      path: Dockerfile
      regexp: 'sonatype/nexus3.*$'
      replace: "sonatype/nexus3:3.19.1"
  - name: REPLACE PLUGIN_VERSION ON DOCKERFILE USING SED COMMAND
    shell: sed -i 's/PLUGIN_VERSION=.*$/PLUGIN_VERSION=0.9.2/g' Dockerfile    
    #- name: Log into DockerHub
    #docker_login:
    #  username: 
    #  password: 
    #  email:
  - name: Build Docker image from Dockerfile
    docker_image:
      name: asadullahkhan/custom-nexus-blobstore-gc:v2
      path: .
      state: build
      #- name: Tag and push to docker hub
      #docker_image:
      #name: asadullahkhan/custom-nexus-blobstore-gc
      #repository: asadullahkhan/custom-nexus-blobstore-gc
      #tag: v2
      #push: no
      

  - name: pusing image thorugh command 
    shell: docker push asadullahkhan/custom-nexus-blobstore-gc:v2


  - name: Create a Deployment by reading the definition from a local file
    k8s:
      state: present
      namespace: default
      src: kubernetes/Deployment.yaml
  - name: Create a Service object by reading the definition from a file
    k8s:
      state: present
      namespace: default
      src: kubernetes/Service.yaml
  - name: Create a Persistent VOlumne by reading the definition from a file
    k8s:
      state: present
      namespace: default
      src: kubernetes/PersistentVolume.yaml
  - name: Create a Persistent Volume Claim by reading the definition from a file
    k8s:
      state: present
      namespace: default
      src: kubernetes/PersistentVolumeClaim.yaml    
    
