kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: nexus-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      volumes:
      - name : pv-vol
        persistentVolumeClaim:
          claimName: nfs-pvc  
      containers:
      - name: container1
        image: asadullahkhan/custom-nexus-blobstore-gc:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/nexuse-data/"
          name: pv-vol
