apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: nexus
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: gce-nfs-disk
    fsType: ext4
